### ISSUE TITLE
need an underdog

### ISSUE THREAD

**Issue by vlraymond** [vlraymond/bootcamp2017#2]
Please describe the story's underdog in a few lines or 1 to 2 paragraphs

**Comment by onudson** [comment]
pushed Underdog.txt directly to branch.

**Comment by vlraymond** [comment]
Thank you! Does the underdog have a name or is it "Underdog"

**Comment by onudson** [comment]
Gesamtkunstwerk?

**Comment by onudson** [comment]
or Dolly.
