### ISSUE TITLE
need a sidekick

### ISSUE THREAD

**Issue by vlraymond** [vlraymond/bootcamp2017#6]
describe sidekick to the story's heroine in a few lines or if you feel like it -  1 to 2 paragraphs

**Comment by tclucas** [comment]
A sentient 17 foot long albino Anaconda named Kit. Has a taste for rodents
and ice cream.

Was raised in a terrarium on Ceres, is familiar with life in gravity and non-gravity situations. Is very cuddly and understands that people mistake hugs for prey-crushing, and has a few emotional issues related to rejection.
